site_name: EMA UI Documentation
theme:
  name: material
docs_dir: .

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_root_full_path: false
            show_object_full_path: false
            show_category_heading: true
            show_if_no_docstring: false

nav:
  - Home: README.md