name: Build and Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Use a recent Python version or get it from .python-version

      - name: Install pipx
        run: |
          sudo apt-get update
          sudo apt-get install -y pipx
          pipx ensurepath

      - name: Install PDM using pipx
        run: |
          pipx install pdm

      - name: Install dependencies
        run: pdm install --no-self --group docs

      - name: Build documentation
        run: pdm run mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
